### ISSUE TITLE
[Peer Testing] Signup asks for starting amount but doesn't save it to account

### ISSUE THREAD

**Issue by kyle-p-may** [tjlarson4/MarketMania#10]
Summary: During signup, the app asks for a starting amount. However, this starting amount doesn't seem to be saved.

Description: While making a new account, it asks for account information. One of the fields asks for a starting amount of money for the app. I entered 10000. After the account is created, I navigated to the accounts page, where it displays account information. At this point, it says my account balance is 0.

Severity: critical

Suggestions/Comments: I am not sure if the balance is associated with that starting amount, but that is what I intuitively thought. If this is the wrong number and it is represented somewhere else, then you could change the name.

**Comment by adguse** [comment]
This worked fine for me
