### ISSUE TITLE
[Peer Testing] Formatting Issues for Company Name on Today's Winners

### ISSUE THREAD

**Issue by kyle-p-may** [tjlarson4/MarketMania#11]
Summary: After clicking on a stock, sometimes the name doesn't wrap properly, so you only see the ending of it.

Description: While at the Home screen, I clicked on the Codiak Biosciences Inc (CDAK) stock information. After this was loaded up, the company name rendered such that you can only see the end of it.

Severity: Trivial

Suggestions/Comments: I would just make sure that you display the beginning and you can always just show a portion of the name.

**Comment by adguse** [comment]
looks fine to me
