### ISSUE TITLE
[Peer Testing] Portfolio items don't show Percent gain

### ISSUE THREAD

**Issue by rtkg12** [tjlarson4/MarketMania#14]
Summary: Items in portfolio always show 0.0% as Percent Gain

Description: Buy a stock. Then search for the stock and check the latest price. Even though average buying price and latest price are different, percent gain still shows 0.

Severity: Blocker (App should display percent gain correctly for portfolio stocks)

Suggestions/comments: It would also help to show more details about the stock in the portfolio such as the latest price, average price, value of owned stocks, etc

**Comment by adguse** [comment]
fixed
