### ISSUE TITLE
[Peer Testing] Sector stocks view

### ISSUE THREAD

**Issue by rtkg12** [tjlarson4/MarketMania#15]
Summary: The stocks in sector view could be displayed better (such as displaying positive gain numbers in green and negatives in red)

Description: Same as summary

Severity: Trivial / Enhancement

Suggestions/comments: The sector view could also be improved by sorting stocks based on popularity as there can be hundreds of thousands of stocks to scroll through. One way to do this would be sorting based on trade volume

**Comment by adguse** [comment]
I added color for gain/loss
