### ISSUE TITLE
[Peer Testing] View Achievements Button on Accounts Page doesn't load a new page

### ISSUE THREAD

**Issue by kyle-p-may** [tjlarson4/MarketMania#8]
Summary: View Achievements Button on Accounts Page doesn't load a new page

Description: The View Achievements Button on Accounts Page doesn't load a new page. It doesn't crash, but it just stays on the Accounts page. There is no output in the development terminal.

Severity: Trivial

Suggestions: I imagine that you are currently implementing this feature; however, if you don't finish it, you could always just remove the button, since it seems like it is somewhat auxiliary to the main features of the app.

**Comment by connor-hanson** [comment]
Removed the button
