### ISSUE TITLE
[Peer Testing] The flow of buying some stocks and then selling them doesn't work

### ISSUE THREAD

**Issue by kyle-p-may** [tjlarson4/MarketMania#9]
Summary: Aftering buying some stocks, it doesn't appear that I can sell them

Description: In order to reproduce this, go to the center button along the bottom banner (with a $ on it). Click this button, click buy stocks, and select one of the stocks. It then asks for how many should be purchased; enter 10. After "purchasing", navigate to the $ button, and select sell. At this point, nothing happens.

Severity: blocker

Suggestions: It looks like the flow is almost complete. The development console says: Can't find keyplane that supports type 4 for keyboard.

**Comment by connor-hanson** [comment]
Feature wasn't implemented yet - sorry
Is fixed
